CC = cl
CFLAGS = /nologo /TC /O2 /W4
LDLIBS = ole32.lib oleaut32.lib shell32.lib shlwapi.lib uuid.lib user32.lib

TARGETS = merge_tabs.exe open_folder_tab.exe

all: $(TARGETS)

merge_tabs.exe: merge_tabs.c explorer_tabs.c explorer_tabs.h
	$(CC) $(CFLAGS) /Fe:$@ merge_tabs.c explorer_tabs.c /link $(LDFLAGS) $(LDLIBS)

open_folder_tab.exe: open_folder_tab.c explorer_tabs.c explorer_tabs.h
	$(CC) $(CFLAGS) /Fe:$@ open_folder_tab.c explorer_tabs.c /link $(LDFLAGS) $(LDLIBS)

clean:
	-del /Q $(TARGETS) *.obj 2>NUL
